/* eslint-disable */
// Generated by scripts/generate-curl-help.mjs — do not edit by hand.

export interface CurlHelpOption {
  short?: string
  long: string
  description: string
}

export interface CurlHelpCategory {
  name: string
  description: string
}

export type CurlHelpPage =
  | {
      kind: 'main'
      options: CurlHelpOption[]
      footer: string[]
    }
  | {
      kind: 'categories'
      categories: CurlHelpCategory[]
    }
  | {
      kind: 'topic'
      title: string
      options: CurlHelpOption[]
    }

export const CURL_HELP_CATEGORIES: CurlHelpCategory[] = [
  {
    "name": "auth",
    "description": "Different types of authentication methods"
  },
  {
    "name": "connection",
    "description": "Low level networking operations"
  },
  {
    "name": "curl",
    "description": "The command line tool itself"
  },
  {
    "name": "dns",
    "description": "General DNS options"
  },
  {
    "name": "file",
    "description": "FILE protocol options"
  },
  {
    "name": "ftp",
    "description": "FTP protocol options"
  },
  {
    "name": "http",
    "description": "HTTP and HTTPS protocol options"
  },
  {
    "name": "imap",
    "description": "IMAP protocol options"
  },
  {
    "name": "misc",
    "description": "Options that don't fit into any other category"
  },
  {
    "name": "output",
    "description": "Filesystem output"
  },
  {
    "name": "pop3",
    "description": "POP3 protocol options"
  },
  {
    "name": "post",
    "description": "HTTP Post specific options"
  },
  {
    "name": "proxy",
    "description": "All options related to proxies"
  },
  {
    "name": "scp",
    "description": "SCP protocol options"
  },
  {
    "name": "sftp",
    "description": "SFTP protocol options"
  },
  {
    "name": "smtp",
    "description": "SMTP protocol options"
  },
  {
    "name": "ssh",
    "description": "SSH protocol options"
  },
  {
    "name": "telnet",
    "description": "TELNET protocol options"
  },
  {
    "name": "tftp",
    "description": "TFTP protocol options"
  },
  {
    "name": "tls",
    "description": "All TLS/SSL related options"
  },
  {
    "name": "upload",
    "description": "All options for uploads"
  },
  {
    "name": "verbose",
    "description": "Options related to any kind of command line output of curl"
  }
]

export const CURL_HELP_PAGES: Record<string, CurlHelpPage> = {
  "": {
    "kind": "main",
    "options": [
      {
        "short": "-d,",
        "long": "--data <data>",
        "description": "HTTP POST data"
      },
      {
        "short": "-f,",
        "long": "--fail",
        "description": "Fail fast with no output on HTTP errors"
      },
      {
        "short": "-h,",
        "long": "--help <category>",
        "description": "Get help for commands"
      },
      {
        "short": "-i,",
        "long": "--include",
        "description": "Include response headers in output"
      },
      {
        "short": "-o,",
        "long": "--output <file>",
        "description": "Write to file instead of stdout"
      },
      {
        "short": "-O,",
        "long": "--remote-name",
        "description": "Write output to file named as remote file"
      },
      {
        "short": "-s,",
        "long": "--silent",
        "description": "Silent mode"
      },
      {
        "short": "-T,",
        "long": "--upload-file <file>",
        "description": "Transfer local FILE to destination"
      },
      {
        "short": "-u,",
        "long": "--user <user:password>",
        "description": "Server user and password"
      },
      {
        "short": "-A,",
        "long": "--user-agent <name>",
        "description": "Send User-Agent <name> to server"
      },
      {
        "short": "-v,",
        "long": "--verbose",
        "description": "Make the operation more talkative"
      },
      {
        "short": "-V,",
        "long": "--version",
        "description": "Show version number and quit"
      }
    ],
    "footer": [
      "This is not the full help, this menu is stripped into categories.",
      "Use \"--help category\" to get an overview of all categories.",
      "For all options use the manual or \"--help all\"."
    ]
  },
  "category": {
    "kind": "categories",
    "categories": [
      {
        "name": "auth",
        "description": "Different types of authentication methods"
      },
      {
        "name": "connection",
        "description": "Low level networking operations"
      },
      {
        "name": "curl",
        "description": "The command line tool itself"
      },
      {
        "name": "dns",
        "description": "General DNS options"
      },
      {
        "name": "file",
        "description": "FILE protocol options"
      },
      {
        "name": "ftp",
        "description": "FTP protocol options"
      },
      {
        "name": "http",
        "description": "HTTP and HTTPS protocol options"
      },
      {
        "name": "imap",
        "description": "IMAP protocol options"
      },
      {
        "name": "misc",
        "description": "Options that don't fit into any other category"
      },
      {
        "name": "output",
        "description": "Filesystem output"
      },
      {
        "name": "pop3",
        "description": "POP3 protocol options"
      },
      {
        "name": "post",
        "description": "HTTP Post specific options"
      },
      {
        "name": "proxy",
        "description": "All options related to proxies"
      },
      {
        "name": "scp",
        "description": "SCP protocol options"
      },
      {
        "name": "sftp",
        "description": "SFTP protocol options"
      },
      {
        "name": "smtp",
        "description": "SMTP protocol options"
      },
      {
        "name": "ssh",
        "description": "SSH protocol options"
      },
      {
        "name": "telnet",
        "description": "TELNET protocol options"
      },
      {
        "name": "tftp",
        "description": "TFTP protocol options"
      },
      {
        "name": "tls",
        "description": "All TLS/SSL related options"
      },
      {
        "name": "upload",
        "description": "All options for uploads"
      },
      {
        "name": "verbose",
        "description": "Options related to any kind of command line output of curl"
      }
    ]
  },
  "auth": {
    "kind": "topic",
    "options": [
      {
        "long": "--anyauth",
        "description": "Pick any authentication method"
      },
      {
        "long": "--aws-sigv4 <provider1[:prvdr2[:reg[:srv]]]>",
        "description": "AWS V4 signature auth"
      },
      {
        "long": "--basic",
        "description": "HTTP Basic Authentication"
      },
      {
        "long": "--delegation <LEVEL>",
        "description": "GSS-API delegation permission"
      },
      {
        "long": "--digest",
        "description": "HTTP Digest Authentication"
      },
      {
        "long": "--ftp-account <data>",
        "description": "Account data string"
      },
      {
        "long": "--location-trusted",
        "description": "Like --location, but send auth to other hosts"
      },
      {
        "long": "--login-options <options>",
        "description": "Server login options"
      },
      {
        "long": "--negotiate",
        "description": "Use HTTP Negotiate (SPNEGO) authentication"
      },
      {
        "long": "--ntlm",
        "description": "HTTP NTLM authentication"
      },
      {
        "long": "--ntlm-wb",
        "description": "HTTP NTLM authentication with winbind"
      },
      {
        "long": "--oauth2-bearer <token>",
        "description": "OAuth 2 Bearer Token"
      },
      {
        "long": "--pass <phrase>",
        "description": "Pass phrase for the private key"
      },
      {
        "long": "--proxy-anyauth",
        "description": "Pick any proxy authentication method"
      },
      {
        "long": "--proxy-basic",
        "description": "Use Basic authentication on the proxy"
      },
      {
        "long": "--proxy-negotiate",
        "description": "HTTP Negotiate (SPNEGO) auth with the proxy"
      },
      {
        "long": "--proxy-ntlm",
        "description": "NTLM authentication with the proxy"
      },
      {
        "long": "--proxy-pass <phrase>",
        "description": "Pass phrase for the private key for HTTPS proxy"
      },
      {
        "long": "--proxy-tlsauthtype <type>",
        "description": "TLS authentication type for HTTPS proxy"
      },
      {
        "long": "--proxy-tlspassword <string>",
        "description": "TLS password for HTTPS proxy"
      },
      {
        "long": "--proxy-tlsuser <name>",
        "description": "TLS username for HTTPS proxy"
      },
      {
        "long": "--proxy-tlsv1",
        "description": "TLSv1 for HTTPS proxy"
      },
      {
        "short": "-U,",
        "long": "--proxy-user <user:password>",
        "description": "Proxy user and password"
      },
      {
        "long": "--pubkey <key>",
        "description": "SSH Public key filename"
      },
      {
        "long": "--sasl-authzid <identity>",
        "description": "Identity for SASL PLAIN authentication"
      },
      {
        "long": "--sasl-ir",
        "description": "Initial response in SASL authentication"
      },
      {
        "long": "--socks5-basic",
        "description": "Username/password auth for SOCKS5 proxies"
      },
      {
        "long": "--socks5-gssapi",
        "description": "Enable GSS-API auth for SOCKS5 proxies"
      },
      {
        "long": "--socks5-gssapi-nec",
        "description": "Compatibility with NEC SOCKS5 server"
      },
      {
        "long": "--socks5-gssapi-service <name>",
        "description": "SOCKS5 proxy service name for GSS-API"
      },
      {
        "long": "--tlsauthtype <type>",
        "description": "TLS authentication type"
      },
      {
        "long": "--tlspassword <string>",
        "description": "TLS password"
      },
      {
        "long": "--tlsuser <name>",
        "description": "TLS username"
      },
      {
        "short": "-u,",
        "long": "--user <user:password>",
        "description": "Server user and password"
      }
    ],
    "title": "auth: Different types of authentication methods"
  },
  "connection": {
    "kind": "topic",
    "options": [
      {
        "long": "--abstract-unix-socket <path>",
        "description": "Connect via abstract Unix domain socket"
      },
      {
        "long": "--connect-timeout <seconds>",
        "description": "Maximum time allowed to connect"
      },
      {
        "long": "--connect-to <HOST1:PORT1:HOST2:PORT2>",
        "description": "Connect to host"
      },
      {
        "short": "-C,",
        "long": "--continue-at <offset>",
        "description": "Resumed transfer offset"
      },
      {
        "long": "--happy-eyeballs-timeout-ms <ms>",
        "description": "Time for IPv6 before IPv4"
      },
      {
        "long": "--interface <name>",
        "description": "Use network INTERFACE (or address)"
      },
      {
        "short": "-4,",
        "long": "--ipv4",
        "description": "Resolve names to IPv4 addresses"
      },
      {
        "short": "-6,",
        "long": "--ipv6",
        "description": "Resolve names to IPv6 addresses"
      },
      {
        "long": "--keepalive-time <seconds>",
        "description": "Interval time for keepalive probes"
      },
      {
        "long": "--limit-rate <speed>",
        "description": "Limit transfer speed to RATE"
      },
      {
        "long": "--local-port <range>",
        "description": "Use a local port number within RANGE"
      },
      {
        "long": "--max-filesize <bytes>",
        "description": "Maximum file size to download"
      },
      {
        "short": "-m,",
        "long": "--max-time <seconds>",
        "description": "Maximum time allowed for transfer"
      },
      {
        "long": "--no-keepalive",
        "description": "Disable TCP keepalive on the connection"
      },
      {
        "short": "-Z,",
        "long": "--parallel",
        "description": "Perform transfers in parallel"
      },
      {
        "long": "--parallel-immediate",
        "description": "Do not wait for multiplexing (with --parallel)"
      },
      {
        "long": "--parallel-max <num>",
        "description": "Maximum concurrency for parallel transfers"
      },
      {
        "long": "--proto <protocols>",
        "description": "Enable/disable PROTOCOLS"
      },
      {
        "long": "--proto-default <protocol>",
        "description": "Use PROTOCOL for any URL missing a scheme"
      },
      {
        "long": "--proto-redir <protocols>",
        "description": "Enable/disable PROTOCOLS on redirect"
      },
      {
        "long": "--rate <max request rate>",
        "description": "Request rate for serial transfers"
      },
      {
        "short": "-X,",
        "long": "--request <method>",
        "description": "Specify request method to use"
      },
      {
        "long": "--resolve <[+]host:port:addr[,addr]...>",
        "description": "Resolve host+port to address"
      },
      {
        "short": "-Y,",
        "long": "--speed-limit <speed>",
        "description": "Stop transfers slower than this"
      },
      {
        "short": "-y,",
        "long": "--speed-time <seconds>",
        "description": "Trigger 'speed-limit' abort after this time"
      },
      {
        "long": "--tcp-fastopen",
        "description": "Use TCP Fast Open"
      },
      {
        "long": "--tcp-nodelay",
        "description": "Set TCP_NODELAY"
      },
      {
        "long": "--unix-socket <path>",
        "description": "Connect through this Unix domain socket"
      }
    ],
    "title": "connection: Low level networking operations"
  },
  "curl": {
    "kind": "topic",
    "options": [
      {
        "short": "-K,",
        "long": "--config <file>",
        "description": "Read config from a file"
      },
      {
        "long": "--create-dirs",
        "description": "Create necessary local directory hierarchy"
      },
      {
        "short": "-q,",
        "long": "--disable",
        "description": "Disable .curlrc"
      },
      {
        "long": "--disallow-username-in-url",
        "description": "Disallow username in URL"
      },
      {
        "long": "--fail-early",
        "description": "Fail on first transfer error"
      },
      {
        "long": "--ftp-create-dirs",
        "description": "Create the remote dirs if not present"
      },
      {
        "short": "-g,",
        "long": "--globoff",
        "description": "Disable URL globbing with {} and []"
      },
      {
        "short": "-h,",
        "long": "--help <category>",
        "description": "Get help for commands"
      },
      {
        "long": "--libcurl <file>",
        "description": "Generate libcurl code for this command line"
      },
      {
        "short": "-M,",
        "long": "--manual",
        "description": "Display the full manual"
      },
      {
        "short": "-n,",
        "long": "--netrc",
        "description": "Must read .netrc for username and password"
      },
      {
        "long": "--netrc-file <filename>",
        "description": "Specify FILE for netrc"
      },
      {
        "long": "--netrc-optional",
        "description": "Use either .netrc or URL"
      },
      {
        "short": "-:,",
        "long": "--next",
        "description": "Make next URL use its separate set of options"
      },
      {
        "short": "-N,",
        "long": "--no-buffer",
        "description": "Disable buffering of the output stream"
      },
      {
        "long": "--no-clobber",
        "description": "Do not overwrite files that already exist"
      },
      {
        "short": "-o,",
        "long": "--output <file>",
        "description": "Write to file instead of stdout"
      },
      {
        "long": "--output-dir <dir>",
        "description": "Directory to save files in"
      },
      {
        "short": "-Z,",
        "long": "--parallel",
        "description": "Perform transfers in parallel"
      },
      {
        "long": "--parallel-immediate",
        "description": "Do not wait for multiplexing (with --parallel)"
      },
      {
        "long": "--parallel-max <num>",
        "description": "Maximum concurrency for parallel transfers"
      },
      {
        "long": "--path-as-is",
        "description": "Do not squash .. sequences in URL path"
      },
      {
        "long": "--proto <protocols>",
        "description": "Enable/disable PROTOCOLS"
      },
      {
        "long": "--proto-default <protocol>",
        "description": "Use PROTOCOL for any URL missing a scheme"
      },
      {
        "long": "--proto-redir <protocols>",
        "description": "Enable/disable PROTOCOLS on redirect"
      },
      {
        "long": "--remove-on-error",
        "description": "Remove output file on errors"
      },
      {
        "long": "--retry <num>",
        "description": "Retry request if transient problems occur"
      },
      {
        "long": "--retry-all-errors",
        "description": "Retry all errors (with --retry)"
      },
      {
        "long": "--retry-connrefused",
        "description": "Retry on connection refused (with --retry)"
      },
      {
        "long": "--retry-delay <seconds>",
        "description": "Wait time between retries"
      },
      {
        "long": "--retry-max-time <seconds>",
        "description": "Retry only within this period"
      },
      {
        "short": "-S,",
        "long": "--show-error",
        "description": "Show error even when -s is used"
      },
      {
        "long": "--url <url>",
        "description": "URL to work with"
      },
      {
        "long": "--variable <[%]name=text/@file>",
        "description": "Set variable"
      },
      {
        "short": "-V,",
        "long": "--version",
        "description": "Show version number and quit"
      }
    ],
    "title": "curl: The command line tool itself"
  },
  "dns": {
    "kind": "topic",
    "options": [
      {
        "long": "--dns-interface <interface>",
        "description": "Interface to use for DNS requests"
      },
      {
        "long": "--dns-ipv4-addr <address>",
        "description": "IPv4 address to use for DNS requests"
      },
      {
        "long": "--dns-ipv6-addr <address>",
        "description": "IPv6 address to use for DNS requests"
      },
      {
        "long": "--dns-servers <addresses>",
        "description": "DNS server addrs to use"
      },
      {
        "long": "--doh-cert-status",
        "description": "Verify DoH server cert status OCSP-staple"
      },
      {
        "long": "--doh-insecure",
        "description": "Allow insecure DoH server connections"
      },
      {
        "long": "--doh-url <URL>",
        "description": "Resolve hostnames over DoH"
      },
      {
        "short": "-4,",
        "long": "--ipv4",
        "description": "Resolve names to IPv4 addresses"
      },
      {
        "short": "-6,",
        "long": "--ipv6",
        "description": "Resolve names to IPv6 addresses"
      },
      {
        "long": "--resolve <[+]host:port:addr[,addr]...>",
        "description": "Resolve host+port to address"
      }
    ],
    "title": "dns: General DNS options"
  },
  "file": {
    "kind": "topic",
    "options": [
      {
        "long": "--create-file-mode <mode>",
        "description": "File mode for created files"
      },
      {
        "short": "-I,",
        "long": "--head",
        "description": "Show document info only"
      },
      {
        "short": "-r,",
        "long": "--range <range>",
        "description": "Retrieve only the bytes within RANGE"
      }
    ],
    "title": "file: FILE protocol options"
  },
  "ftp": {
    "kind": "topic",
    "options": [
      {
        "short": "-a,",
        "long": "--append",
        "description": "Append to target file when uploading"
      },
      {
        "long": "--crlf",
        "description": "Convert LF to CRLF in upload"
      },
      {
        "long": "--disable-eprt",
        "description": "Inhibit using EPRT or LPRT"
      },
      {
        "long": "--disable-epsv",
        "description": "Inhibit using EPSV"
      },
      {
        "short": "-D,",
        "long": "--dump-header <filename>",
        "description": "Write the received headers to <filename>"
      },
      {
        "long": "--ftp-account <data>",
        "description": "Account data string"
      },
      {
        "long": "--ftp-alternative-to-user <command>",
        "description": "String to replace USER [name]"
      },
      {
        "long": "--ftp-create-dirs",
        "description": "Create the remote dirs if not present"
      },
      {
        "long": "--ftp-method <method>",
        "description": "Control CWD usage"
      },
      {
        "long": "--ftp-pasv",
        "description": "Send PASV/EPSV instead of PORT"
      },
      {
        "short": "-P,",
        "long": "--ftp-port <address>",
        "description": "Send PORT instead of PASV"
      },
      {
        "long": "--ftp-pret",
        "description": "Send PRET before PASV"
      },
      {
        "long": "--ftp-skip-pasv-ip",
        "description": "Skip the IP address for PASV"
      },
      {
        "long": "--ftp-ssl-ccc",
        "description": "Send CCC after authenticating"
      },
      {
        "long": "--ftp-ssl-ccc-mode <active/passive>",
        "description": "Set CCC mode"
      },
      {
        "long": "--ftp-ssl-control",
        "description": "Require TLS for login, clear for transfer"
      },
      {
        "short": "-I,",
        "long": "--head",
        "description": "Show document info only"
      },
      {
        "long": "--ignore-content-length",
        "description": "Ignore the size of the remote resource"
      },
      {
        "long": "--krb <level>",
        "description": "Enable Kerberos with security <level>"
      },
      {
        "short": "-l,",
        "long": "--list-only",
        "description": "List only mode"
      },
      {
        "short": "-Q,",
        "long": "--quote <command>",
        "description": "Send command(s) to server before transfer"
      },
      {
        "short": "-r,",
        "long": "--range <range>",
        "description": "Retrieve only the bytes within RANGE"
      },
      {
        "short": "-z,",
        "long": "--time-cond <time>",
        "description": "Transfer based on a time condition"
      }
    ],
    "title": "ftp: FTP protocol options"
  },
  "http": {
    "kind": "topic",
    "options": [
      {
        "long": "--alt-svc <filename>",
        "description": "Enable alt-svc with this cache file"
      },
      {
        "long": "--anyauth",
        "description": "Pick any authentication method"
      },
      {
        "long": "--aws-sigv4 <provider1[:prvdr2[:reg[:srv]]]>",
        "description": "AWS V4 signature auth"
      },
      {
        "long": "--compressed",
        "description": "Request compressed response"
      },
      {
        "short": "-b,",
        "long": "--cookie <data|filename>",
        "description": "Send cookies from string/load from file"
      },
      {
        "short": "-c,",
        "long": "--cookie-jar <filename>",
        "description": "Save cookies to <filename> after operation"
      },
      {
        "short": "-d,",
        "long": "--data <data>",
        "description": "HTTP POST data"
      },
      {
        "long": "--data-ascii <data>",
        "description": "HTTP POST ASCII data"
      },
      {
        "long": "--data-binary <data>",
        "description": "HTTP POST binary data"
      },
      {
        "long": "--data-raw <data>",
        "description": "HTTP POST data, '@' allowed"
      },
      {
        "long": "--data-urlencode <data>",
        "description": "HTTP POST data URL encoded"
      },
      {
        "long": "--digest",
        "description": "HTTP Digest Authentication"
      },
      {
        "short": "-D,",
        "long": "--dump-header <filename>",
        "description": "Write the received headers to <filename>"
      },
      {
        "long": "--etag-compare <file>",
        "description": "Load ETag from file"
      },
      {
        "long": "--etag-save <file>",
        "description": "Parse incoming ETag and save to a file"
      },
      {
        "long": "--expect100-timeout <seconds>",
        "description": "How long to wait for 100-continue"
      },
      {
        "short": "-f,",
        "long": "--fail",
        "description": "Fail fast with no output on HTTP errors"
      },
      {
        "long": "--fail-with-body",
        "description": "Fail on HTTP errors but save the body"
      },
      {
        "short": "-F,",
        "long": "--form <name=content>",
        "description": "Specify multipart MIME data"
      },
      {
        "long": "--form-escape",
        "description": "Escape form fields using backslash"
      },
      {
        "long": "--form-string <name=string>",
        "description": "Specify multipart MIME data"
      },
      {
        "short": "-G,",
        "long": "--get",
        "description": "Put the post data in the URL and use GET"
      },
      {
        "long": "--haproxy-clientip <ip>",
        "description": "Set address in HAProxy PROXY"
      },
      {
        "long": "--haproxy-protocol",
        "description": "Send HAProxy PROXY protocol v1 header"
      },
      {
        "short": "-I,",
        "long": "--head",
        "description": "Show document info only"
      },
      {
        "short": "-H,",
        "long": "--header <header/@file>",
        "description": "Pass custom header(s) to server"
      },
      {
        "long": "--hsts <filename>",
        "description": "Enable HSTS with this cache file"
      },
      {
        "long": "--http2",
        "description": "Use HTTP/2"
      },
      {
        "long": "--http2-prior-knowledge",
        "description": "Use HTTP 2 without HTTP/1.1 Upgrade"
      },
      {
        "long": "--http3",
        "description": "Use HTTP v3"
      },
      {
        "long": "--http3-only",
        "description": "Use HTTP v3 only"
      },
      {
        "long": "--ignore-content-length",
        "description": "Ignore the size of the remote resource"
      },
      {
        "long": "--json <data>",
        "description": "HTTP POST JSON"
      },
      {
        "short": "-j,",
        "long": "--junk-session-cookies",
        "description": "Ignore session cookies read from file"
      },
      {
        "short": "-L,",
        "long": "--location",
        "description": "Follow redirects"
      },
      {
        "long": "--location-trusted",
        "description": "Like --location, but send auth to other hosts"
      },
      {
        "long": "--max-redirs <num>",
        "description": "Maximum number of redirects allowed"
      },
      {
        "long": "--negotiate",
        "description": "Use HTTP Negotiate (SPNEGO) authentication"
      },
      {
        "long": "--no-alpn",
        "description": "Disable the ALPN TLS extension"
      },
      {
        "long": "--no-npn",
        "description": "Disable the NPN TLS extension"
      },
      {
        "long": "--ntlm",
        "description": "HTTP NTLM authentication"
      },
      {
        "long": "--ntlm-wb",
        "description": "HTTP NTLM authentication with winbind"
      },
      {
        "long": "--post301",
        "description": "Do not switch to GET after a 301 redirect"
      },
      {
        "long": "--post302",
        "description": "Do not switch to GET after a 302 redirect"
      },
      {
        "long": "--post303",
        "description": "Do not switch to GET after a 303 redirect"
      },
      {
        "long": "--proxy-http2",
        "description": "Use HTTP/2 with HTTPS proxy"
      },
      {
        "short": "-r,",
        "long": "--range <range>",
        "description": "Retrieve only the bytes within RANGE"
      },
      {
        "long": "--raw",
        "description": "Do HTTP raw; no transfer decoding"
      },
      {
        "short": "-e,",
        "long": "--referer <URL>",
        "description": "Referrer URL"
      },
      {
        "long": "--request-target <path>",
        "description": "Specify the target for this request"
      },
      {
        "short": "-z,",
        "long": "--time-cond <time>",
        "description": "Transfer based on a time condition"
      },
      {
        "long": "--tr-encoding",
        "description": "Request compressed transfer encoding"
      },
      {
        "long": "--url-query <data>",
        "description": "Add a URL query part"
      },
      {
        "short": "-A,",
        "long": "--user-agent <name>",
        "description": "Send User-Agent <name> to server"
      }
    ],
    "title": "http: HTTP and HTTPS protocol options"
  },
  "imap": {
    "kind": "topic",
    "options": [
      {
        "short": "-H,",
        "long": "--header <header/@file>",
        "description": "Pass custom header(s) to server"
      },
      {
        "long": "--login-options <options>",
        "description": "Server login options"
      }
    ],
    "title": "imap: IMAP protocol options"
  },
  "misc": {
    "kind": "topic",
    "options": [
      {
        "long": "--metalink",
        "description": "Process given URLs as metalink XML file"
      },
      {
        "long": "--random-file <file>",
        "description": "File for reading random data from"
      },
      {
        "long": "--service-name <name>",
        "description": "SPNEGO service name"
      },
      {
        "short": "-B,",
        "long": "--use-ascii",
        "description": "Use ASCII/text transfer"
      },
      {
        "long": "--xattr",
        "description": "Store metadata in extended file attributes"
      }
    ],
    "title": "misc: Options that don't fit into any other category"
  },
  "output": {
    "kind": "topic",
    "options": [
      {
        "long": "--fail-with-body",
        "description": "Fail on HTTP errors but save the body"
      },
      {
        "long": "--no-clobber",
        "description": "Do not overwrite files that already exist"
      },
      {
        "short": "-J,",
        "long": "--remote-header-name",
        "description": "Use the header-provided filename"
      },
      {
        "short": "-O,",
        "long": "--remote-name",
        "description": "Write output to file named as remote file"
      },
      {
        "long": "--remote-name-all",
        "description": "Use the remote filename for all URLs"
      },
      {
        "short": "-R,",
        "long": "--remote-time",
        "description": "Set remote file's time on local output"
      }
    ],
    "title": "output: Filesystem output"
  },
  "pop3": {
    "kind": "topic",
    "options": [
      {
        "short": "-l,",
        "long": "--list-only",
        "description": "List only mode"
      },
      {
        "long": "--login-options <options>",
        "description": "Server login options"
      }
    ],
    "title": "pop3: POP3 protocol options"
  },
  "post": {
    "kind": "topic",
    "options": [
      {
        "short": "-d,",
        "long": "--data <data>",
        "description": "HTTP POST data"
      },
      {
        "long": "--data-ascii <data>",
        "description": "HTTP POST ASCII data"
      },
      {
        "long": "--data-binary <data>",
        "description": "HTTP POST binary data"
      },
      {
        "long": "--data-raw <data>",
        "description": "HTTP POST data, '@' allowed"
      },
      {
        "long": "--data-urlencode <data>",
        "description": "HTTP POST data URL encoded"
      },
      {
        "long": "--json <data>",
        "description": "HTTP POST JSON"
      },
      {
        "long": "--post301",
        "description": "Do not switch to GET after a 301 redirect"
      },
      {
        "long": "--post302",
        "description": "Do not switch to GET after a 302 redirect"
      },
      {
        "long": "--post303",
        "description": "Do not switch to GET after a 303 redirect"
      },
      {
        "long": "--url-query <data>",
        "description": "Add a URL query part"
      }
    ],
    "title": "post: HTTP Post specific options"
  },
  "proxy": {
    "kind": "topic",
    "options": [
      {
        "long": "--anyauth",
        "description": "Pick any authentication method"
      },
      {
        "long": "--digest",
        "description": "HTTP Digest Authentication"
      },
      {
        "long": "--haproxy-clientip <ip>",
        "description": "Set address in HAProxy PROXY"
      },
      {
        "long": "--haproxy-protocol",
        "description": "Send HAProxy PROXY protocol v1 header"
      },
      {
        "long": "--noproxy <no-proxy-list>",
        "description": "List of hosts which do not use proxy"
      },
      {
        "long": "--preproxy [protocol://]host[:port]",
        "description": "Use this proxy first"
      },
      {
        "short": "-x,",
        "long": "--proxy [protocol://]host[:port]",
        "description": "Use this proxy"
      },
      {
        "long": "--proxy-anyauth",
        "description": "Pick any proxy authentication method"
      },
      {
        "long": "--proxy-basic",
        "description": "Use Basic authentication on the proxy"
      },
      {
        "long": "--proxy-cacert <file>",
        "description": "CA certificates to verify proxy against"
      },
      {
        "long": "--proxy-capath <dir>",
        "description": "CA directory to verify proxy against"
      },
      {
        "long": "--proxy-cert <cert[:passwd]>",
        "description": "Set client certificate for proxy"
      },
      {
        "long": "--proxy-cert-type <type>",
        "description": "Client certificate type for HTTPS proxy"
      },
      {
        "long": "--proxy-ciphers <list>",
        "description": "SSL ciphers to use for proxy"
      },
      {
        "long": "--proxy-crlfile <file>",
        "description": "Set a CRL list for proxy"
      },
      {
        "long": "--proxy-digest",
        "description": "Digest auth with the proxy"
      },
      {
        "long": "--proxy-header <header/@file>",
        "description": "Pass custom header(s) to proxy"
      },
      {
        "long": "--proxy-http2",
        "description": "Use HTTP/2 with HTTPS proxy"
      },
      {
        "long": "--proxy-insecure",
        "description": "Skip HTTPS proxy cert verification"
      },
      {
        "long": "--proxy-key <key>",
        "description": "Private key for HTTPS proxy"
      },
      {
        "long": "--proxy-key-type <type>",
        "description": "Private key file type for proxy"
      },
      {
        "long": "--proxy-negotiate",
        "description": "HTTP Negotiate (SPNEGO) auth with the proxy"
      },
      {
        "long": "--proxy-ntlm",
        "description": "NTLM authentication with the proxy"
      },
      {
        "long": "--proxy-pass <phrase>",
        "description": "Pass phrase for the private key for HTTPS proxy"
      },
      {
        "long": "--proxy-pinnedpubkey <hashes>",
        "description": "FILE/HASHES public key to verify proxy with"
      },
      {
        "long": "--proxy-service-name <name>",
        "description": "SPNEGO proxy service name"
      },
      {
        "long": "--proxy-ssl-allow-beast",
        "description": "Allow security flaw for interop for HTTPS proxy"
      },
      {
        "long": "--proxy-ssl-auto-client-cert",
        "description": "Auto client certificate for proxy"
      },
      {
        "long": "--proxy-tls13-ciphers <ciphersuite list>",
        "description": "TLS 1.3 proxy cipher suites"
      },
      {
        "long": "--proxy-tlsauthtype <type>",
        "description": "TLS authentication type for HTTPS proxy"
      },
      {
        "long": "--proxy-tlspassword <string>",
        "description": "TLS password for HTTPS proxy"
      },
      {
        "long": "--proxy-tlsuser <name>",
        "description": "TLS username for HTTPS proxy"
      },
      {
        "long": "--proxy-tlsv1",
        "description": "TLSv1 for HTTPS proxy"
      },
      {
        "short": "-U,",
        "long": "--proxy-user <user:password>",
        "description": "Proxy user and password"
      },
      {
        "short": "-p,",
        "long": "--proxytunnel",
        "description": "HTTP proxy tunnel (using CONNECT)"
      },
      {
        "long": "--socks4 <host[:port]>",
        "description": "SOCKS4 proxy on given host + port"
      },
      {
        "long": "--socks4a <host[:port]>",
        "description": "SOCKS4a proxy on given host + port"
      },
      {
        "long": "--socks5 <host[:port]>",
        "description": "SOCKS5 proxy on given host + port"
      },
      {
        "long": "--socks5-basic",
        "description": "Username/password auth for SOCKS5 proxies"
      },
      {
        "long": "--socks5-gssapi",
        "description": "Enable GSS-API auth for SOCKS5 proxies"
      },
      {
        "long": "--socks5-gssapi-nec",
        "description": "Compatibility with NEC SOCKS5 server"
      },
      {
        "long": "--socks5-gssapi-service <name>",
        "description": "SOCKS5 proxy service name for GSS-API"
      },
      {
        "long": "--socks5-hostname <host[:port]>",
        "description": "SOCKS5 proxy, pass hostname to proxy"
      },
      {
        "long": "--suppress-connect-headers",
        "description": "Suppress proxy CONNECT response headers"
      }
    ],
    "title": "proxy: All options related to proxies"
  },
  "scp": {
    "kind": "topic",
    "options": [
      {
        "long": "--compressed-ssh",
        "description": "Enable SSH compression"
      },
      {
        "long": "--create-file-mode <mode>",
        "description": "File mode for created files"
      },
      {
        "long": "--hostpubmd5 <md5>",
        "description": "Acceptable MD5 hash of host public key"
      },
      {
        "long": "--hostpubsha256 <sha256>",
        "description": "Acceptable SHA256 hash of host public key"
      },
      {
        "short": "-k,",
        "long": "--insecure",
        "description": "Allow insecure server connections"
      },
      {
        "long": "--pubkey <key>",
        "description": "SSH Public key filename"
      }
    ],
    "title": "scp: SCP protocol options"
  },
  "sftp": {
    "kind": "topic",
    "options": [
      {
        "short": "-a,",
        "long": "--append",
        "description": "Append to target file when uploading"
      },
      {
        "long": "--create-file-mode <mode>",
        "description": "File mode for created files"
      },
      {
        "long": "--ftp-create-dirs",
        "description": "Create the remote dirs if not present"
      },
      {
        "long": "--hostpubmd5 <md5>",
        "description": "Acceptable MD5 hash of host public key"
      },
      {
        "long": "--hostpubsha256 <sha256>",
        "description": "Acceptable SHA256 hash of host public key"
      },
      {
        "short": "-k,",
        "long": "--insecure",
        "description": "Allow insecure server connections"
      },
      {
        "short": "-l,",
        "long": "--list-only",
        "description": "List only mode"
      },
      {
        "long": "--pubkey <key>",
        "description": "SSH Public key filename"
      },
      {
        "short": "-Q,",
        "long": "--quote <command>",
        "description": "Send command(s) to server before transfer"
      },
      {
        "short": "-r,",
        "long": "--range <range>",
        "description": "Retrieve only the bytes within RANGE"
      }
    ],
    "title": "sftp: SFTP protocol options"
  },
  "smtp": {
    "kind": "topic",
    "options": [
      {
        "long": "--crlf",
        "description": "Convert LF to CRLF in upload"
      },
      {
        "short": "-H,",
        "long": "--header <header/@file>",
        "description": "Pass custom header(s) to server"
      },
      {
        "long": "--login-options <options>",
        "description": "Server login options"
      },
      {
        "long": "--mail-auth <address>",
        "description": "Originator address of the original email"
      },
      {
        "long": "--mail-from <address>",
        "description": "Mail from this address"
      },
      {
        "long": "--mail-rcpt <address>",
        "description": "Mail to this address"
      },
      {
        "long": "--mail-rcpt-allowfails",
        "description": "Allow RCPT TO command to fail"
      }
    ],
    "title": "smtp: SMTP protocol options"
  },
  "ssh": {
    "kind": "topic",
    "options": [
      {
        "long": "--compressed-ssh",
        "description": "Enable SSH compression"
      },
      {
        "long": "--key <key>",
        "description": "Private key filename"
      },
      {
        "long": "--pass <phrase>",
        "description": "Pass phrase for the private key"
      }
    ],
    "title": "ssh: SSH protocol options"
  },
  "telnet": {
    "kind": "topic",
    "options": [
      {
        "short": "-t,",
        "long": "--telnet-option <opt=val>",
        "description": "Set telnet option"
      }
    ],
    "title": "telnet: TELNET protocol options"
  },
  "tftp": {
    "kind": "topic",
    "options": [
      {
        "long": "--tftp-blksize <value>",
        "description": "Set TFTP BLKSIZE option"
      },
      {
        "long": "--tftp-no-options",
        "description": "Do not send any TFTP options"
      }
    ],
    "title": "tftp: TFTP protocol options"
  },
  "tls": {
    "kind": "topic",
    "options": [
      {
        "long": "--ca-native",
        "description": "Load CA certs from the OS"
      },
      {
        "long": "--cacert <file>",
        "description": "CA certificate to verify peer against"
      },
      {
        "long": "--capath <dir>",
        "description": "CA directory to verify peer against"
      },
      {
        "short": "-E,",
        "long": "--cert <certificate[:password]>",
        "description": "Client certificate file and password"
      },
      {
        "long": "--cert-status",
        "description": "Verify server cert status OCSP-staple"
      },
      {
        "long": "--cert-type <type>",
        "description": "Certificate type (DER/PEM/ENG/P12)"
      },
      {
        "long": "--ciphers <list of ciphers>",
        "description": "SSL ciphers to use"
      },
      {
        "long": "--crlfile <file>",
        "description": "Certificate Revocation list"
      },
      {
        "long": "--curves <list>",
        "description": "(EC) TLS key exchange algorithms to request"
      },
      {
        "long": "--doh-cert-status",
        "description": "Verify DoH server cert status OCSP-staple"
      },
      {
        "long": "--doh-insecure",
        "description": "Allow insecure DoH server connections"
      },
      {
        "long": "--egd-file <file>",
        "description": "EGD socket path for random data"
      },
      {
        "long": "--engine <name>",
        "description": "Crypto engine to use"
      },
      {
        "long": "--false-start",
        "description": "Enable TLS False Start"
      },
      {
        "long": "--ftp-ssl-ccc",
        "description": "Send CCC after authenticating"
      },
      {
        "long": "--ftp-ssl-ccc-mode <active/passive>",
        "description": "Set CCC mode"
      },
      {
        "long": "--ftp-ssl-control",
        "description": "Require TLS for login, clear for transfer"
      },
      {
        "short": "-k,",
        "long": "--insecure",
        "description": "Allow insecure server connections"
      },
      {
        "long": "--key <key>",
        "description": "Private key filename"
      },
      {
        "long": "--key-type <type>",
        "description": "Private key file type (DER/PEM/ENG)"
      },
      {
        "long": "--no-alpn",
        "description": "Disable the ALPN TLS extension"
      },
      {
        "long": "--no-npn",
        "description": "Disable the NPN TLS extension"
      },
      {
        "long": "--no-sessionid",
        "description": "Disable SSL session-ID reusing"
      },
      {
        "long": "--pass <phrase>",
        "description": "Pass phrase for the private key"
      },
      {
        "long": "--pinnedpubkey <hashes>",
        "description": "FILE/HASHES Public key to verify peer against"
      },
      {
        "long": "--proxy-ca-native",
        "description": "Load CA certs from the OS to verify proxy"
      },
      {
        "long": "--proxy-cacert <file>",
        "description": "CA certificates to verify proxy against"
      },
      {
        "long": "--proxy-capath <dir>",
        "description": "CA directory to verify proxy against"
      },
      {
        "long": "--proxy-cert <cert[:passwd]>",
        "description": "Set client certificate for proxy"
      },
      {
        "long": "--proxy-cert-type <type>",
        "description": "Client certificate type for HTTPS proxy"
      },
      {
        "long": "--proxy-ciphers <list>",
        "description": "SSL ciphers to use for proxy"
      },
      {
        "long": "--proxy-crlfile <file>",
        "description": "Set a CRL list for proxy"
      },
      {
        "long": "--proxy-digest",
        "description": "Digest auth with the proxy"
      },
      {
        "long": "--proxy-insecure",
        "description": "Skip HTTPS proxy cert verification"
      },
      {
        "long": "--proxy-key <key>",
        "description": "Private key for HTTPS proxy"
      },
      {
        "long": "--proxy-key-type <type>",
        "description": "Private key file type for proxy"
      },
      {
        "long": "--proxy-pass <phrase>",
        "description": "Pass phrase for the private key for HTTPS proxy"
      },
      {
        "long": "--proxy-pinnedpubkey <hashes>",
        "description": "FILE/HASHES public key to verify proxy with"
      },
      {
        "long": "--proxy-service-name <name>",
        "description": "SPNEGO proxy service name"
      },
      {
        "long": "--proxy-ssl-allow-beast",
        "description": "Allow security flaw for interop for HTTPS proxy"
      },
      {
        "long": "--proxy-ssl-auto-client-cert",
        "description": "Auto client certificate for proxy"
      },
      {
        "long": "--proxy-tls13-ciphers <ciphersuite list>",
        "description": "TLS 1.3 proxy cipher suites"
      },
      {
        "long": "--proxy-tlsauthtype <type>",
        "description": "TLS authentication type for HTTPS proxy"
      },
      {
        "long": "--proxy-tlspassword <string>",
        "description": "TLS password for HTTPS proxy"
      },
      {
        "long": "--proxy-tlsuser <name>",
        "description": "TLS username for HTTPS proxy"
      },
      {
        "long": "--proxy-tlsv1",
        "description": "TLSv1 for HTTPS proxy"
      },
      {
        "long": "--ssl",
        "description": "Try enabling TLS"
      },
      {
        "long": "--ssl-allow-beast",
        "description": "Allow security flaw to improve interop"
      },
      {
        "long": "--ssl-auto-client-cert",
        "description": "Use auto client certificate (Schannel)"
      },
      {
        "long": "--ssl-no-revoke",
        "description": "Disable cert revocation checks (Schannel)"
      },
      {
        "long": "--ssl-reqd",
        "description": "Require SSL/TLS"
      },
      {
        "long": "--ssl-revoke-best-effort",
        "description": "Ignore missing cert CRL dist points"
      },
      {
        "short": "-2,",
        "long": "--sslv2",
        "description": "SSLv2"
      },
      {
        "short": "-3,",
        "long": "--sslv3",
        "description": "SSLv3"
      },
      {
        "long": "--tls-max <VERSION>",
        "description": "Maximum allowed TLS version"
      },
      {
        "long": "--tls13-ciphers <list>",
        "description": "TLS 1.3 cipher suites to use"
      },
      {
        "long": "--tlsauthtype <type>",
        "description": "TLS authentication type"
      },
      {
        "long": "--tlspassword <string>",
        "description": "TLS password"
      },
      {
        "long": "--tlsuser <name>",
        "description": "TLS username"
      },
      {
        "short": "-1,",
        "long": "--tlsv1",
        "description": "TLSv1.0 or greater"
      }
    ],
    "title": "tls: All TLS/SSL related options"
  },
  "upload": {
    "kind": "topic",
    "options": [
      {
        "long": "--create-file-mode <mode>",
        "description": "File mode for created files"
      },
      {
        "short": "-d,",
        "long": "--data <data>",
        "description": "HTTP POST data"
      },
      {
        "long": "--data-ascii <data>",
        "description": "HTTP POST ASCII data"
      },
      {
        "long": "--data-binary <data>",
        "description": "HTTP POST binary data"
      },
      {
        "long": "--data-raw <data>",
        "description": "HTTP POST data, '@' allowed"
      },
      {
        "long": "--data-urlencode <data>",
        "description": "HTTP POST data URL encoded"
      },
      {
        "short": "-F,",
        "long": "--form <name=content>",
        "description": "Specify multipart MIME data"
      },
      {
        "long": "--form-escape",
        "description": "Escape form fields using backslash"
      },
      {
        "long": "--form-string <name=string>",
        "description": "Specify multipart MIME data"
      },
      {
        "short": "-G,",
        "long": "--get",
        "description": "Put the post data in the URL and use GET"
      },
      {
        "long": "--json <data>",
        "description": "HTTP POST JSON"
      },
      {
        "short": "-T,",
        "long": "--upload-file <file>",
        "description": "Transfer local FILE to destination"
      },
      {
        "long": "--url-query <data>",
        "description": "Add a URL query part"
      }
    ],
    "title": "upload: All options for uploads"
  },
  "verbose": {
    "kind": "topic",
    "options": [
      {
        "short": "-i,",
        "long": "--include",
        "description": "Include response headers in output"
      },
      {
        "long": "--no-progress-meter",
        "description": "Do not show the progress meter"
      },
      {
        "short": "-#,",
        "long": "--progress-bar",
        "description": "Display transfer progress as a bar"
      },
      {
        "short": "-s,",
        "long": "--silent",
        "description": "Silent mode"
      },
      {
        "long": "--stderr <file>",
        "description": "Where to redirect stderr"
      },
      {
        "long": "--styled-output",
        "description": "Enable styled output for HTTP headers"
      },
      {
        "long": "--trace <file>",
        "description": "Write a debug trace to FILE"
      },
      {
        "long": "--trace-ascii <file>",
        "description": "Like --trace, but without hex output"
      },
      {
        "long": "--trace-config <string>",
        "description": "Details to log in trace/verbose output"
      },
      {
        "long": "--trace-ids",
        "description": "Transfer + connection ids in verbose output"
      },
      {
        "long": "--trace-time",
        "description": "Add time stamps to trace/verbose output"
      },
      {
        "short": "-v,",
        "long": "--verbose",
        "description": "Make the operation more talkative"
      },
      {
        "short": "-w,",
        "long": "--write-out <format>",
        "description": "Output FORMAT after completion"
      }
    ],
    "title": "verbose: Options related to any kind of command line output of curl"
  }
}

export function curlHelpPage(name: string): CurlHelpPage {
  return CURL_HELP_PAGES[name] ?? CURL_HELP_PAGES['']
}
